/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Process.*;
import java.sql.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

/**
 *
 * @author HoangDuoc
 */
public class Search extends javax.swing.JInternalFrame {

    DefaultComboBoxModel model1 = new DefaultComboBoxModel();
    DefaultComboBoxModel model2 = new DefaultComboBoxModel();
    DefaultComboBoxModel model3 = new DefaultComboBoxModel();
    DefaultComboBoxModel model4 = new DefaultComboBoxModel();
    private String st1 = "SELECT TenNXB FROM librarymanagement.nhaxuatban";
    private String st2 = "SELECT languageName FROM librarymanagement.language";
    private String st3 = "SELECT TenTacGia FROM librarymanagement.tacgia";
    private String st4 = "SELECT TenLinhVuc FROM librarymanagement.linhvuc";

    /**
     * Creates new form Tracuu
     */
    public Search() {
        initComponents();
        init();
        
    }

    public void init() {
        Googlesearch.loaddataCombo(st1, model1, 1, cbbNxb);
        Googlesearch.loaddataCombo(st2, model2, 1, cbbNgonngu);
        Googlesearch.loaddataCombo(st3, model3, 1, cbbTacgia);
        Googlesearch.loaddataCombo(st4, model4, 1, cbbLinhvuc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        rbNxb = new javax.swing.JRadioButton();
        rbTen = new javax.swing.JRadioButton();
        cbbNxb = new javax.swing.JComboBox();
        tfTen = new javax.swing.JTextField();
        rbNgonngu = new javax.swing.JRadioButton();
        cbbNgonngu = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        rbMasach = new javax.swing.JRadioButton();
        tfMasach = new javax.swing.JTextField();
        rbTacgia = new javax.swing.JRadioButton();
        cbbTacgia = new javax.swing.JComboBox();
        rbLinhvuc = new javax.swing.JRadioButton();
        cbbLinhvuc = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setTitle("Giao Diện Tìm Kiếm");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tra cứu sách"));

        buttonGroup1.add(rbNxb);
        rbNxb.setText("Tìm theo nhà xuất bản");
        rbNxb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbNxbMouseClicked(evt);
            }
        });

        buttonGroup1.add(rbTen);
        rbTen.setText("Tìm theo tên");
        rbTen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbTenMouseClicked(evt);
            }
        });
        rbTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTenActionPerformed(evt);
            }
        });

        cbbNxb.setEnabled(false);

        tfTen.setEnabled(false);
        tfTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTenActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbNgonngu);
        rbNgonngu.setText("Tìm theo ngôn ngữ");
        rbNgonngu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbNgonnguMouseClicked(evt);
            }
        });

        cbbNgonngu.setEnabled(false);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/dilai.png"))); // NOI18N
        jButton1.setText("Tra cứu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbMasach);
        rbMasach.setText("Tìm theo mã sách");
        rbMasach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbMasachMouseClicked(evt);
            }
        });
        rbMasach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMasachActionPerformed(evt);
            }
        });

        tfMasach.setToolTipText("");
        tfMasach.setEnabled(false);
        tfMasach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMasachActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbTacgia);
        rbTacgia.setText("Tìm theo tác giả");
        rbTacgia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbTacgiaMouseClicked(evt);
            }
        });

        cbbTacgia.setEnabled(false);

        buttonGroup1.add(rbLinhvuc);
        rbLinhvuc.setText("Tìm theo lĩnh vực");
        rbLinhvuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbLinhvucMouseClicked(evt);
            }
        });

        cbbLinhvuc.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbTen)
                    .addComponent(rbNgonngu)
                    .addComponent(rbNxb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfTen, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbNxb, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbNgonngu, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbMasach)
                    .addComponent(rbTacgia)
                    .addComponent(rbLinhvuc))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbbLinhvuc, 0, 219, Short.MAX_VALUE)
                    .addComponent(tfMasach)
                    .addComponent(cbbTacgia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(332, 332, 332))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbTen)
                    .addComponent(tfTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbMasach)
                    .addComponent(tfMasach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbNxb)
                    .addComponent(cbbNxb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbTacgia)
                    .addComponent(cbbTacgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbNgonngu)
                    .addComponent(cbbNgonngu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbLinhvuc)
                    .addComponent(cbbLinhvuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Kết quả"));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(table);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/WifiTrak.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTenActionPerformed

    private void rbTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTenActionPerformed

    }//GEN-LAST:event_rbTenActionPerformed

    private void rbTenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbTenMouseClicked
        tfTen.setEnabled(true);
        tfTen.requestFocus();
        tfMasach.setText("");
        tfMasach.setEnabled(false);
        cbbTacgia.setEnabled(false);
        cbbLinhvuc.setEnabled(false);
        cbbNxb.setEnabled(false);
        cbbNgonngu.setEnabled(false);
    }//GEN-LAST:event_rbTenMouseClicked

    private void rbNxbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbNxbMouseClicked
        tfTen.setText("");
        tfMasach.setText("");
        tfTen.setEnabled(false);
        cbbNxb.setEnabled(true);
        cbbNgonngu.setEnabled(false);
        tfMasach.setEnabled(false);
        cbbTacgia.setEnabled(false);
        cbbLinhvuc.setEnabled(false);
    }//GEN-LAST:event_rbNxbMouseClicked

    private void rbNgonnguMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbNgonnguMouseClicked
        tfTen.setText("");
        tfMasach.setText("");
        tfTen.setEnabled(false);
        cbbNxb.setEnabled(false);
        cbbNgonngu.setEnabled(true);
        tfMasach.setEnabled(false);
        cbbTacgia.setEnabled(false);
        cbbLinhvuc.setEnabled(false);
    }//GEN-LAST:event_rbNgonnguMouseClicked

    private void rbMasachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbMasachMouseClicked
        tfTen.setText("");
        tfTen.setEnabled(false);
        cbbNxb.setEnabled(false);
        cbbNgonngu.setEnabled(false);
        tfMasach.setEnabled(true);
        tfMasach.requestFocus();
        cbbTacgia.setEnabled(false);
        cbbLinhvuc.setEnabled(false);
    }//GEN-LAST:event_rbMasachMouseClicked

    private void rbTacgiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbTacgiaMouseClicked
        tfTen.setText("");
        tfMasach.setText("");
        tfTen.setEnabled(false);
        cbbNxb.setEnabled(false);
        cbbNgonngu.setEnabled(false);
        tfMasach.setEnabled(false);
        cbbTacgia.setEnabled(true);
        cbbLinhvuc.setEnabled(false);
    }//GEN-LAST:event_rbTacgiaMouseClicked

    private void rbLinhvucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbLinhvucMouseClicked
        tfTen.setText("");
        tfMasach.setText("");
        tfTen.setEnabled(false);
        cbbNxb.setEnabled(false);
        cbbNgonngu.setEnabled(false);
        tfMasach.setEnabled(false);
        cbbTacgia.setEnabled(false);
        cbbLinhvuc.setEnabled(true);
    }//GEN-LAST:event_rbLinhvucMouseClicked

    private void tfMasachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMasachActionPerformed

    }//GEN-LAST:event_tfMasachActionPerformed

    private void rbMasachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMasachActionPerformed

    }//GEN-LAST:event_rbMasachActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (rbTen.isSelected()) {
            if (tfTen.getText().length() == 0) {
                JOptionPane.showMessageDialog(null, "Bạn chưa nhập thông tin", "Thông báo", 1);
                tfTen.requestFocus();
            } else {
                Googlesearch.loadtableTen(tfTen.getText(), table);
            }
        } else if (rbMasach.isSelected()) {
            if (tfMasach.getText().length() == 0) {
                JOptionPane.showMessageDialog(null, "Bạn chưa nhập thông tin", "Thông báo", 1);
                tfMasach.requestFocus();
            } else {
                Googlesearch.loadtableMS(tfMasach.getText(), table);
            }
        } else if (rbNxb.isSelected()) {
            Googlesearch.loadtableNxb(cbbNxb.getSelectedItem().toString(), table);
        } else if (rbNgonngu.isSelected()) {
            Googlesearch.loadtableNgonngu(cbbNgonngu.getSelectedItem().toString(), table);
        } else if (rbTacgia.isSelected()) {
            Googlesearch.loadtableTacgia(cbbTacgia.getSelectedItem().toString(), table);
        } else if (rbLinhvuc.isSelected()) {
            Googlesearch.loadtableLinhvuc(cbbLinhvuc.getSelectedItem().toString(), table);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbbLinhvuc;
    private javax.swing.JComboBox cbbNgonngu;
    private javax.swing.JComboBox cbbNxb;
    private javax.swing.JComboBox cbbTacgia;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rbLinhvuc;
    private javax.swing.JRadioButton rbMasach;
    private javax.swing.JRadioButton rbNgonngu;
    private javax.swing.JRadioButton rbNxb;
    private javax.swing.JRadioButton rbTacgia;
    private javax.swing.JRadioButton rbTen;
    private javax.swing.JTable table;
    private javax.swing.JTextField tfMasach;
    private javax.swing.JTextField tfTen;
    // End of variables declaration//GEN-END:variables
}
