/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;
import java.sql.*;
import javax.swing.*;
import Process.*;
import javax.swing.JOptionPane;
import Process.Tacgia;

/**
 *
 * @author tiendat
 */
public class Author extends javax.swing.JInternalFrame{
   public static String sql = "SELECT *from quanlythuvien.tacgia order by MaTG asc";
   public static String malop;
   

    /**
     * Creates new form Author
     */
   
    public Author() {
        initComponents();
        ShowTG();
        ProcessTG(false);
        
    }
    public void ShowTG(){
         UpdateTable.LoadData(sql, tabletacgia);
         this.lb1.setText("Tổng số có "+this.tabletacgia.getRowCount()+" Tác giả ");
    }
    public  void ProcessTG(boolean  b){
        this.btedit.setEnabled(b);
        this.btxoa.setEnabled(b);
        this.btadd.setEnabled(b);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabletacgia = new javax.swing.JTable();
        jLabelmatacgia = new javax.swing.JLabel();
        jLabelten = new javax.swing.JLabel();
        txtMatacgia = new javax.swing.JTextField();
        txtTentacgia = new javax.swing.JTextField();
        btnhap = new javax.swing.JButton();
        bthome = new javax.swing.JButton();
        lb1 = new javax.swing.JLabel();
        btexit = new javax.swing.JButton();
        btadd = new javax.swing.JButton();
        btsearch = new javax.swing.JButton();
        txtlook1 = new javax.swing.JTextField();
        btedit = new javax.swing.JButton();
        btxoa = new javax.swing.JButton();
        jLabeldiachi = new javax.swing.JLabel();
        txtdiachi = new javax.swing.JTextField();

        jLabel3.setText("jLabel3");

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabletacgia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabletacgia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabletacgiaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabletacgia);

        jLabelmatacgia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelmatacgia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/kate.png"))); // NOI18N
        jLabelmatacgia.setText("Mã tác giả");

        jLabelten.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelten.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/UserManager.png"))); // NOI18N
        jLabelten.setText("Tên tác giả");

        btnhap.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add user.png"))); // NOI18N
        btnhap.setText("Nhập mới");
        btnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapActionPerformed(evt);
            }
        });

        bthome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bthome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/dilai.png"))); // NOI18N
        bthome.setText("Reset");
        bthome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthomeActionPerformed(evt);
            }
        });

        lb1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/UserManager.png"))); // NOI18N
        lb1.setText("Tổng số có tác giả");

        btexit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/exit_1.gif"))); // NOI18N
        btexit.setText("Exit");
        btexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexitActionPerformed(evt);
            }
        });

        btadd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add user.png"))); // NOI18N
        btadd.setText("Add");
        btadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaddActionPerformed(evt);
            }
        });

        btsearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search_48.png"))); // NOI18N
        btsearch.setText("Search");
        btsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsearchActionPerformed(evt);
            }
        });

        txtlook1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlook1ActionPerformed(evt);
            }
        });

        btedit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/editdelete.png"))); // NOI18N
        btedit.setText("Edit");
        btedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteditActionPerformed(evt);
            }
        });

        btxoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/help.png"))); // NOI18N
        btxoa.setText("Delete");
        btxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxoaActionPerformed(evt);
            }
        });

        jLabeldiachi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabeldiachi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/29_House_32x32.png"))); // NOI18N
        jLabeldiachi.setText("Địa Chỉ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelmatacgia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabeldiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelten))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMatacgia, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtdiachi, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtTentacgia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnhap, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(btadd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtlook1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(btsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(886, 886, 886))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bthome))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1074, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btedit, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(229, 229, 229)
                                .addComponent(btxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(184, 184, 184)
                                .addComponent(btexit, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMatacgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelmatacgia)
                            .addComponent(txtlook1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTentacgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelten, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabeldiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btadd))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btedit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btxoa)
                            .addComponent(btexit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bthome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb1))
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bthomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthomeActionPerformed
        // TODO add your handling code here:
         ShowTG();
        ProcessTG(false);
        this.txtlook1.setText(null);
    }//GEN-LAST:event_bthomeActionPerformed

    private void btexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btexitActionPerformed
        // TODO add your handling code here:
         if(JOptionPane.showConfirmDialog(null,"Bạn có chắc chắn muốn thoát chương trình hay không","thông báo ",2)==0)
            this.dispose();
    }//GEN-LAST:event_btexitActionPerformed

    private void txtlook1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlook1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtlook1ActionPerformed

    private void tabletacgiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabletacgiaMouseClicked
        // TODO add your handling code here:
        ProcessTG(true);
        this.btadd.setEnabled(false);
        try{
        int row = this.tabletacgia.getSelectedRow();
        String IDrow = (this.tabletacgia.getModel().getValueAt(row, 0).toString());
        String sql2=" Select *from quanlythuvien.tacgia where MaTG ='"+IDrow+"'";
        ResultSet rs = UpdateTable.ShowTextField(sql2);
        if(rs.next()){
            malop = rs.getString("MaTG");
            this.txtMatacgia.setText(rs.getString("MaTG"));
            this.txtTentacgia.setText((rs.getString("TenTacGia")));
            this.txtdiachi.setText((rs.getString("diachi")));
            
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            
        }
        
    }//GEN-LAST:event_tabletacgiaMouseClicked

    private void btaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaddActionPerformed
        // TODO add your handling code here:
        if(this.txtMatacgia.getText().length()==0)
            JOptionPane.showMessageDialog(null,"mã tác giả không được bỏ trống","thông báo",1);
        else 
            if(this.txtMatacgia.getText().length()>10)
                JOptionPane.showMessageDialog(null,"mã tác giả không được vượt quá 10 kí tự","thông báo",1);
        else
                if(this.txtTentacgia.getText().length() ==0)
                    JOptionPane.showMessageDialog(null,"tên tác giả không được bỏ trống","thông báo",1);
        else
                    if(this.txtdiachi.getText().length()==0){
                        JOptionPane.showMessageDialog(null,"địa chỉ không được bỏ trống","thông báo",1);
                    }
                else {
                    Tacgia.InsertTG(this.txtMatacgia.getText().trim(),this.txtTentacgia.getText(),this.txtdiachi.getText());
                    ShowTG();
                    ProcessTG(false);
                }
                   
                        
    }//GEN-LAST:event_btaddActionPerformed

    private void btnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapActionPerformed
        // TODO add your handling code here:
        ProcessTG(false);
        this.btadd.setEnabled(true);
        this.txtMatacgia.setText(null);
        this.txtTentacgia.setText(null);
    }//GEN-LAST:event_btnhapActionPerformed

    private void bteditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteditActionPerformed
        // TODO add your handling code here:
          if(this.txtMatacgia.getText().length()==0)
            JOptionPane.showMessageDialog(null,"mã tác giả không thể bỏ trống","thông báo",1);
        else 
            if(this.txtMatacgia.getText().length()>10)
                JOptionPane.showMessageDialog(null,"mã tác giả không được vượt 10 kí tự","thông báo",1);
        else
                if(this.txtTentacgia.getText().length() ==0)
                    JOptionPane.showMessageDialog(null,"tên tác giả không được bỏ trống ","thông báo",1);
        else
                    if(this.txtdiachi.getText().length() == 0){
                        JOptionPane.showMessageDialog(null,"địa chỉ không được bỏ trống","thông báo",1);
                    }
                else {
                    Tacgia.UpdateTG(malop,this.txtMatacgia.getText().trim(), this.txtTentacgia.getText(),this.txtdiachi.getText());
                    ShowTG();
                    ProcessTG(false);
                }
    }//GEN-LAST:event_bteditActionPerformed

    private void btxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxoaActionPerformed
        // TODO add your handling code here:
        if(this.txtMatacgia.getText().length()==0)
            JOptionPane.showMessageDialog(null,"bạn cần chọn để xóa","thong bao",1);
        else
        {
            if(JOptionPane.showConfirmDialog(null,"bạn có chắc muốn xóa tác giả "+malop+"hay khong?","thong bao",2) ==0)
                Tacgia.DeleteTG(malop);
            ShowTG();
                    ProcessTG(false);
        }
    }//GEN-LAST:event_btxoaActionPerformed

    private void btsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsearchActionPerformed
        // TODO add your handling code here:
     if(this.txtlook1.getText().length()==0)
            JOptionPane.showMessageDialog(null,"bạn chưa nhập từ khóa cần tìm","thông báo",1);
        else
        {
            String sql1 = "SELECT * FROM quanlythuvien.tacgia where MaTG like '%" +this.txtlook1.getText()+"%' or TenTacGia like '%" +this.txtlook1.getText()+"%'";
            UpdateTable.LoadData(sql1, tabletacgia);
            this.lb1.setText(" Có " +this.tabletacgia.getRowCount()+ " tên tác giả cần tìm ");
        }
       
    }//GEN-LAST:event_btsearchActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btadd;
    private javax.swing.JButton btedit;
    private javax.swing.JButton btexit;
    private javax.swing.JButton bthome;
    private javax.swing.JButton btnhap;
    private javax.swing.JButton btsearch;
    private javax.swing.JButton btxoa;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabeldiachi;
    private javax.swing.JLabel jLabelmatacgia;
    private javax.swing.JLabel jLabelten;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb1;
    private javax.swing.JTable tabletacgia;
    private javax.swing.JTextField txtMatacgia;
    private javax.swing.JTextField txtTentacgia;
    private javax.swing.JTextField txtdiachi;
    private javax.swing.JTextField txtlook1;
    // End of variables declaration//GEN-END:variables
}
