/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import static Main.Login.manv;
import static Main.Login.rs;
import Process.checkLog;
import java.awt.RenderingHints.Key;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author HoangDuoc
 */
public class Login extends javax.swing.JFrame {

    public static ResultSet rs = null;
    public static PreparedStatement pst = null;
    public static String manv = null;

    public Login() {

        this.setLocation(400, 150);
        initComponents();
        lbConn.setText(checkLog.testConnect());
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfUser = new javax.swing.JTextField();
        jpPass = new javax.swing.JPasswordField();
        lbConn = new javax.swing.JLabel();
        btLog = new javax.swing.JButton();
        btReset = new javax.swing.JButton();
        btExit = new javax.swing.JButton();
        cbChedo = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng Nhập");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin đăng nhập"));
        jPanel1.setForeground(new java.awt.Color(0, 0, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Windows-Log-Off-icon.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setText("Tên Đăng Nhập");

        jLabel3.setText("Mật khẩu");

        tfUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUserActionPerformed(evt);
            }
        });
        tfUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfUserKeyPressed(evt);
            }
        });

        jpPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpPassActionPerformed(evt);
            }
        });
        jpPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpPassKeyPressed(evt);
            }
        });

        lbConn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbConn.setForeground(new java.awt.Color(0, 0, 255));
        lbConn.setText("Kết nối thành công !!");

        btLog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pause.png"))); // NOI18N
        btLog.setText("Đăng Nhập");
        btLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogActionPerformed(evt);
            }
        });
        btLog.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btLogKeyPressed(evt);
            }
        });

        btReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/dilai.png"))); // NOI18N
        btReset.setText("Nhập Lại");
        btReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetActionPerformed(evt);
            }
        });

        btExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/new.png"))); // NOI18N
        btExit.setText("Thoát");
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });

        cbChedo.setText("Chế độ quản lý");
        cbChedo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbChedoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfUser, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(jpPass))
                        .addGap(17, 17, 17))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(lbConn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(28, Short.MAX_VALUE)
                                .addComponent(btLog)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbChedo)
                                    .addComponent(btReset))
                                .addGap(18, 18, 18)))
                        .addComponent(btExit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(tfUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jpPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbChedo)
                        .addGap(27, 27, 27)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLog, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btReset, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btExit, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbConn))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUserActionPerformed

    private void btResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetActionPerformed
        tfUser.setText("");
        jpPass.setText("");
        tfUser.requestFocus();
    }//GEN-LAST:event_btResetActionPerformed

    private void btLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogActionPerformed
        if (tfUser.getText().length() == 0 || String.valueOf(jpPass.getPassword()).length() == 0) {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập tài khoản hoặc mật khẩu", "Thông báo", JOptionPane.WARNING_MESSAGE);
        } else {
           
            if (cbChedo.isSelected()) {
                rs = checkLog.cLognv(tfUser.getText(), String.valueOf(jpPass.getPassword()));
                try {
                    if (rs.next()) {
                        //Dang nhap thanh cong
                        manv = tfUser.getText();
                        Main main = new Main();
                        main.getMnDanhmuc().setEnabled(true);
                        main.getMnDocgia().setEnabled(true);
                        main.getMnQlsach().setEnabled(true);
                        main.getMnThongke().setEnabled(true);
                        this.setVisible(false);
                        main.setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(null, "Tài khoản không tồn tại", "Lỗi đăng nhập", 0);
                        tfUser.requestFocus();
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e, "Thông báo", 1);
                }
            } else {
                rs = checkLog.cLogdg(tfUser.getText(), String.valueOf(jpPass.getPassword()));
                try {
                    if (rs.next()) {
                        //Dang nhap thanh cong
                        manv = tfUser.getText();
                        Main main = new Main();
                        this.setVisible(false);
                        main.setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(null, "Tai khoan khong ton tai", "Loi dang nhap", 0);
                        tfUser.requestFocus();
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e, "Thong bao", 1);
                }
            }
        }

    }//GEN-LAST:event_btLogActionPerformed

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn thoát chương trình", "Lưu ý", 2) == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_btExitActionPerformed

    private void jpPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpPassActionPerformed

    private void btLogKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btLogKeyPressed

    }//GEN-LAST:event_btLogKeyPressed

    private void jpPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpPassKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (tfUser.getText().length() == 0 || String.valueOf(jpPass.getPassword()).length() == 0) {
                JOptionPane.showMessageDialog(null, "Ban chua nhap tai khoan hoac mat khau", "Thong bao", JOptionPane.WARNING_MESSAGE);
            } else {
               
                if (cbChedo.isSelected()) {
                    rs = checkLog.cLognv(tfUser.getText(), String.valueOf(jpPass.getPassword()));
                    try {
                        if (rs.next()) {
                            //Dang nhap thanh cong
                            manv = tfUser.getText();
                            Main main = new Main();
                            main.getMnDanhmuc().setEnabled(true);
                            main.getMnDocgia().setEnabled(true);
                            main.getMnQlsach().setEnabled(true);
                            main.getMnThongke().setEnabled(true);
                            this.setVisible(false);
                            main.setVisible(true);
                        } else {
                            JOptionPane.showMessageDialog(null, "Tai khoan khong ton tai", "Loi dang nhap", 0);
                            tfUser.requestFocus();
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e, "Thong bao", 1);
                    }
                } else {
                    rs = checkLog.cLogdg(tfUser.getText(), String.valueOf(jpPass.getPassword()));
                    try {
                        if (rs.next()) {
                            //Dang nhap thanh cong
                            manv = tfUser.getText();
                            Main main = new Main();
                            this.setVisible(false);
                            main.setVisible(true);
                        } else {
                            JOptionPane.showMessageDialog(null, "Tai khoan khong ton tai", "Loi dang nhap", 0);
                            tfUser.requestFocus();
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e, "Thong bao", 1);
                    }
                }
            }
    }//GEN-LAST:event_jpPassKeyPressed
    }
    private void tfUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfUserKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (tfUser.getText().length() == 0 || String.valueOf(jpPass.getPassword()).length() == 0) {
                JOptionPane.showMessageDialog(null, "Ban chua nhap tai khoan hoac mat khau", "Thong bao", JOptionPane.WARNING_MESSAGE);
            } else {
                if (cbChedo.isSelected()) {
                    rs = checkLog.cLognv(tfUser.getText(), String.valueOf(jpPass.getPassword()));
                    try {
                        if (rs.next()) {
                            //Dang nhap thanh cong
                            manv = tfUser.getText();
                            Main main = new Main();
                            main.getMnDanhmuc().setEnabled(true);
                            main.getMnDocgia().setEnabled(true);
                            main.getMnQlsach().setEnabled(true);
                            main.getMnThongke().setEnabled(true);
                            this.setVisible(false);
                            main.setVisible(true);
                        } else {
                            JOptionPane.showMessageDialog(null, "Tai khoan khong ton tai", "Loi dang nhap", 0);
                            tfUser.requestFocus();
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e, "Thong bao", 1);
                    }
                } else {
                    rs = checkLog.cLogdg(tfUser.getText(), String.valueOf(jpPass.getPassword()));
                    try {
                        if (rs.next()) {
                            //Dang nhap thanh cong
                            manv = tfUser.getText();
                            Main main = new Main();
                            this.setVisible(false);
                            main.setVisible(true);
                        } else {
                            JOptionPane.showMessageDialog(null, "Tai khoan khong ton tai", "Loi dang nhap", 0);
                            tfUser.requestFocus();
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e, "Thong bao", 1);
                    }
                }
            }
        }
    }//GEN-LAST:event_tfUserKeyPressed

    private void cbChedoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbChedoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbChedoActionPerformed

    public JCheckBox getCbChedo() {
        return cbChedo;
    }

    public void setCbChedo(JCheckBox cbChedo) {
        this.cbChedo = cbChedo;
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);

            }
        });
    }

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExit;
    private javax.swing.JButton btLog;
    private javax.swing.JButton btReset;
    private javax.swing.JCheckBox cbChedo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jpPass;
    private javax.swing.JLabel lbConn;
    private javax.swing.JTextField tfUser;
    // End of variables declaration//GEN-END:variables
}
