/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.*;
import Process.*;

/**
 *
 * @author tiendat
 */
public class ManagementUser extends javax.swing.JInternalFrame {

 public static String sql = "SELECT * FROM quanlythuvien.docgia order by TenDG asc ";
 public static String madocgia; //luu tam ma khi nhan len 1 dong trong bang phuc vu trong ham Update
    public ManagementUser() {
        initComponents();
        //goi ham do du lieu len bang
        ShowDG();
        ProcessDG(false);
    }
    public void ShowDG(){
         UpdateTable.LoadData(sql, table);
         this.lbTong.setText("Tổng số có "+this.table.getRowCount()+" Mã độc giả ");
    }
//phuong thuc nay dung de dieu khien cac nut button
    public void ProcessDG(boolean  b){
        this.btAdd.setEnabled(b);
        this.btEdit.setEnabled(b);
        this.btExit.setEnabled(b);
        this.btdelete.setEnabled(b);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btAdd = new javax.swing.JButton();
        btdelete = new javax.swing.JButton();
        btEdit = new javax.swing.JButton();
        btExit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtTDG = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMDG = new javax.swing.JTextField();
        btnew = new javax.swing.JButton();
        txtlook = new javax.swing.JTextField();
        btlook = new javax.swing.JButton();
        lbTong = new javax.swing.JLabel();
        btRefest = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("jButton1");

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setForeground(new java.awt.Color(0, 255, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/list_Borrow.png"))); // NOI18N
        jLabel1.setText("User Management");

        btAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add user.png"))); // NOI18N
        btAdd.setText("Add");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        btdelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btdelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/editdelete.png"))); // NOI18N
        btdelete.setText("Delete");
        btdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdeleteActionPerformed(evt);
            }
        });

        btEdit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/edit_add.png"))); // NOI18N
        btEdit.setText("Edit");
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });

        btExit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/exit.gif"))); // NOI18N
        btExit.setText("Exit");
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.setToolTipText("");
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/UserManager.png"))); // NOI18N
        jLabel2.setText("Tên độc giả");

        txtTDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTDGActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/agt_login.png"))); // NOI18N
        jLabel3.setText("Mã độc giả");

        btnew.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Loai BK tong hop.png"))); // NOI18N
        btnew.setText("Nhập mới");
        btnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnewActionPerformed(evt);
            }
        });

        txtlook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlookActionPerformed(evt);
            }
        });

        btlook.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btlook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search_48.png"))); // NOI18N
        btlook.setText("Looking for");
        btlook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlookActionPerformed(evt);
            }
        });

        lbTong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user_business_32.png"))); // NOI18N
        lbTong.setText("Tổng số độc giả");

        btRefest.setBackground(new java.awt.Color(255, 255, 255));
        btRefest.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btRefest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/dilai.png"))); // NOI18N
        btRefest.setText("Reset");
        btRefest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRefestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTong, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btRefest, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btlook))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(165, 165, 165)
                                                .addComponent(btAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(95, 95, 95)
                                                .addComponent(btdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(105, 105, 105)
                                                .addComponent(btEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtlook, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(164, 164, 164))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(103, 103, 103)
                                                .addComponent(btExit, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))))))
                        .addContainerGap(62, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtMDG, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtTDG, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(68, 68, 68)
                        .addComponent(btnew)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtlook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btlook)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTDG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnew))))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMDG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdd)
                    .addComponent(btdelete)
                    .addComponent(btEdit)
                    .addComponent(btExit))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTong, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRefest))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdeleteActionPerformed
           if(this.txtMDG.getText().length() == 0)
           JOptionPane.showMessageDialog(null,"Bạn cần chọn mã độc giả để xóa ","thông báo",1);
           else
           {
               if(JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa "+madocgia+"hay không?","thông báo",2) == 0 )
                   User.DeleteDG(madocgia);
               ShowDG();
               ProcessDG(false);
                   
                   }
           
    }//GEN-LAST:event_btdeleteActionPerformed

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
       if(this.txtMDG.getText().length() == 0)
           JOptionPane.showMessageDialog(null,"mã độc giả không thể bỏ trống","thông báo",1);
       else
           if(this.txtMDG.getText().length()>20)
               JOptionPane.showMessageDialog(null,"mã độc giả không được vượt quá 20 kí tự","thông báo",1);
       else
               if(this.txtTDG.getText().length()==0)
                   JOptionPane.showMessageDialog(null,"tên độc giả không được bỏ trống","thông báo",1);
               
           
               else{
                   User.InsertDG(this.txtMDG.getText().trim(),this.txtTDG.getText());
                   ShowDG();
                   ProcessDG(false);
               }
    }//GEN-LAST:event_btAddActionPerformed

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
        if(JOptionPane.showConfirmDialog(null,"bạn có chắc chắn muốn thoát chương trình hay không","thông báo ",2)==0)
            this.dispose();
    }//GEN-LAST:event_btExitActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        ProcessDG(true);
        this.btAdd.setEnabled(false);
        try{
            int row = this.table.getSelectedRow();
            String IDrow = (this.table.getModel().getValueAt(row, 0).toString());
           String sql1 ="SELECT * FROM quanlythuvien.docgia where MaDG = '"+IDrow+"'";
           //du lieu hien thi len textfield
           ResultSet rs = UpdateTable.ShowTextField(sql1);
           if(rs.next())
           {
               
               madocgia = rs.getString("MaDG");
               
               this.txtMDG.setText(rs.getString("MaDG"));
                 this.txtTDG.setText(rs.getString("TenDG"));
              
               
           }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_tableMouseClicked

    private void txtTDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTDGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTDGActionPerformed

    private void txtlookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlookActionPerformed

    private void btnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnewActionPerformed
        ProcessDG(false);
        this.btAdd.setEnabled(true);
        this.txtTDG.setText(null);
        this.txtMDG.setText(null);
    }//GEN-LAST:event_btnewActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed
        if(this.txtMDG.getText().length() == 0)
           JOptionPane.showMessageDialog(null,"mã độc giả không thể bỏ trống","thông báo",1);
       else
           if(this.txtMDG.getText().length()>20)
               JOptionPane.showMessageDialog(null,"mã độc giả không được vượt quá 20 kí tự","thông báo",1);
       else
               if(this.txtTDG.getText().length()==0)
                   JOptionPane.showMessageDialog(null,"tên độc giả không được bỏ trống","thông báo",1);
               else{
                   User.UpdateDG(madocgia,this.txtMDG.getText().trim(), this.txtTDG.getText());
                   ShowDG();
                   ProcessDG(false);
               }
    }//GEN-LAST:event_btEditActionPerformed

    private void btlookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlookActionPerformed
        if(this.txtlook.getText().length()==0)
            JOptionPane.showMessageDialog(null,"bạn chưa nhập từ khóa cần tìm","thông báo",1);
        else
        {
            String sql1 = "SELECT *from quanlythuvien.docgia where MaDG like '%" +this.txtlook.getText()+"%' or TenDG like '%" +this.txtlook.getText()+"%'";
            UpdateTable.LoadData(sql1, table);
            this.lbTong.setText(" Có " +this.table.getRowCount()+ " tên độc giả cần tìm ");
        }
    }//GEN-LAST:event_btlookActionPerformed

    private void btRefestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRefestActionPerformed
        ShowDG();
        ProcessDG(false);
        this.txtlook.setText(null);
    }//GEN-LAST:event_btRefestActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btEdit;
    private javax.swing.JButton btExit;
    private javax.swing.JButton btRefest;
    private javax.swing.JButton btdelete;
    private javax.swing.JButton btlook;
    private javax.swing.JButton btnew;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbTong;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtMDG;
    private javax.swing.JTextField txtTDG;
    private javax.swing.JTextField txtlook;
    // End of variables declaration//GEN-END:variables
}
