/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.sql.*;
import javax.swing.*;
import Process.*;
import Process.NXB;

/**
 *
 * @author tiendat
 */
public class Publisher extends javax.swing.JInternalFrame {
    public static String sql ="SELECT * FROM quanlythuvien.nhaxuatban order by MaNXB asc";
    public static String malop;//bien nay dung de luu tru tam thoi
    public void ShowNXB(){
        UpdateTable.LoadData(sql, tableNXB);
        this.lbnxb.setText(" Tổng số có "+this.tableNXB.getRowCount()+" nhà xuất bản ");
    }
    public void ProcessNXB(boolean  b){
        this.btAddNXB.setEnabled(b);
        this.btEditNXB.setEnabled(b);
//        this.btExitNXB.setEnabled(b);
        this.btxoanxb.setEnabled(b);
        
    }
    

    /**
     * Creates new form Publisher
     */
    public Publisher() {
        initComponents();
        ShowNXB();
        ProcessNXB(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtmanxb = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTenNXB = new javax.swing.JTextField();
        btnhap1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableNXB = new javax.swing.JTable();
        btAddNXB = new javax.swing.JButton();
        btEditNXB = new javax.swing.JButton();
        btxoanxb = new javax.swing.JButton();
        btExitNXB = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtSearchNXB = new javax.swing.JTextField();
        lbnxb = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtdiachi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtphone = new javax.swing.JTextField();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logout.png"))); // NOI18N
        jLabel1.setText("Mã NXB");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Users_1.png"))); // NOI18N
        jLabel2.setText("Tên NXB");

        txtTenNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenNXBActionPerformed(evt);
            }
        });

        btnhap1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnhap1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add user.png"))); // NOI18N
        btnhap1.setText("Nhập mới");
        btnhap1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhap1ActionPerformed(evt);
            }
        });

        tableNXB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableNXB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNXBMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableNXB);

        btAddNXB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btAddNXB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/agt_login.png"))); // NOI18N
        btAddNXB.setText("Add");
        btAddNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddNXBActionPerformed(evt);
            }
        });

        btEditNXB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btEditNXB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/edit_add.png"))); // NOI18N
        btEditNXB.setText("Edit");
        btEditNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditNXBActionPerformed(evt);
            }
        });

        btxoanxb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btxoanxb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/editdelete.png"))); // NOI18N
        btxoanxb.setText("Delete");
        btxoanxb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxoanxbActionPerformed(evt);
            }
        });

        btExitNXB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btExitNXB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/exit.gif"))); // NOI18N
        btExitNXB.setText("Exit");
        btExitNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitNXBActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/dilai.png"))); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search_48.png"))); // NOI18N
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        lbnxb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbnxb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user_business_32.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add user.png"))); // NOI18N
        jLabel3.setText("Địa Chỉ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/edit_add.png"))); // NOI18N
        jLabel4.setText("Điện Thoại");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbnxb, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(721, 721, 721)
                                .addComponent(jButton2))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1076, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtmanxb, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                    .addComponent(txtTenNXB)
                                    .addComponent(txtdiachi)
                                    .addComponent(txtphone))
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnhap1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btAddNXB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(btEditNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                                .addComponent(btxoanxb)
                                .addGap(79, 79, 79)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(txtSearchNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(btExitNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(250, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmanxb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtTenNXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnhap1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSearchNXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btAddNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btEditNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btxoanxb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btExitNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbnxb))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenNXBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenNXBActionPerformed

    private void btAddNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddNXBActionPerformed
        // TODO add your handling code here:
         if(this.txtmanxb.getText().length()==0)
            JOptionPane.showMessageDialog(null,"ma nha xuat khong duoc bo trong","thong bao",1);
        else 
            if(this.txtmanxb.getText().length()>10)
                JOptionPane.showMessageDialog(null,"ma tac gia khong duoc vuot qua 10 ki tu","thong bao",1);
        else
                if(this.txtTenNXB.getText().length() ==0)
                    JOptionPane.showMessageDialog(null,"tên tác giả không được bỏ trống","thông báo",1);
                else if(this.txtdiachi.getText().length()== 0)
                    JOptionPane.showMessageDialog(null,"tên địa chỉ không được bỏ trống");
                else if(this.txtphone.getText().length() ==0)
                    JOptionPane.showMessageDialog(null,"tên phone không được bỏ trống","thông báo",1);
                else {
                    NXB.InsertNXB(this.txtmanxb.getText().trim(),this.txtTenNXB.getText(),this.txtdiachi.getText(),this.txtphone.getText());
                    ShowNXB();
                    ProcessNXB(false);
                }
    }//GEN-LAST:event_btAddNXBActionPerformed

    private void btxoanxbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxoanxbActionPerformed
        // TODO add your handling code here:
         if(this.txtmanxb.getText().length()==0)
            JOptionPane.showMessageDialog(null,"ban can chon de xoa","thong bao",1);
        else
        {
            if(JOptionPane.showConfirmDialog(null,"ban co chac muon xoa tac gia "+malop+"hay khong?","thong bao",2) ==0)
                NXB.DeleteNXB(malop);
            ShowNXB();
                    ProcessNXB(false);
        }
    }//GEN-LAST:event_btxoanxbActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          ShowNXB();
        ProcessNXB(false);
        this.txtSearchNXB.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnhap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhap1ActionPerformed
        // TODO add your handling code here:
        ProcessNXB(false);
        this.btAddNXB.setEnabled(true);
        this.txtTenNXB.setText(null);
        this.txtmanxb.setText(null);
    }//GEN-LAST:event_btnhap1ActionPerformed

    private void btEditNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditNXBActionPerformed
        // TODO add your handling code here:
        if(this.txtmanxb.getText().length()==0)
            JOptionPane.showMessageDialog(null,"mã nhà xuất bản không được bỏ trống","thông báo",1);
        else 
            if(this.txtmanxb.getText().length()>10)
                JOptionPane.showMessageDialog(null,"mã nhà xuất bản không được vượt quá 10 kí tự","thông báo",1);
        else
                if(this.txtTenNXB.getText().length() ==0)
                    JOptionPane.showMessageDialog(null,"tên tác giả không được bỏ trống","thông báo",1);
                else if(this.txtdiachi.getText().length()==0)
                    JOptionPane.showMessageDialog(null,"địa chỉ không được bỏ trống","thông báo",1);
                else 
                    if(this.txtphone.getText().length() == 0)
                    JOptionPane.showMessageDialog(null,"Phone không được bỏ trống","thông báo",1);
                else {
                    NXB.UpdateNXB(malop,this.txtmanxb.getText().trim(),this.txtTenNXB.getText(),this.txtdiachi.getText(),this.txtphone.getText());
                    ShowNXB();
                    ProcessNXB(false);
                }
    }//GEN-LAST:event_btEditNXBActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(this.txtSearchNXB.getText().length()==0)
            JOptionPane.showMessageDialog(null,"bạn chưa nhập từ khóa cần tìm","thông báo",1);
        else
        {
            String sql1 = "SELECT * FROM quanlythuvien.nhaxuatban where MaNXB like '%" +this.txtSearchNXB.getText()+"%' or TenNXB like '%" +this.txtSearchNXB.getText()+"%'";
            UpdateTable.LoadData(sql1, tableNXB);
            this.lbnxb.setText(" Có " +this.tableNXB.getRowCount()+ " tên nhà xuất bản cần tìm ");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tableNXBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNXBMouseClicked
        // TODO add your handling code here:
         ProcessNXB(true);
        this.btAddNXB.setEnabled(false);
        try{
        int row = this.tableNXB.getSelectedRow();
        String IDrow = (this.tableNXB.getModel().getValueAt(row, 0).toString());
        String sql2=" SELECT * FROM quanlythuvien.nhaxuatban where MaNXB = '"+IDrow+"'";
        ResultSet rs = UpdateTable.ShowTextField(sql2);
        if(rs.next()){
            malop = rs.getString("MaNXB");
            this.txtmanxb.setText(rs.getString("MaNXB"));
            this.txtTenNXB.setText((rs.getString("TenNXB")));
            this.txtdiachi.setText(rs.getString("DiaChi"));
            this.txtphone.setText(rs.getString("DienThoai"));
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            
        }
    }//GEN-LAST:event_tableNXBMouseClicked

    private void btExitNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitNXBActionPerformed
        // TODO add your handling code here:
         if(JOptionPane.showConfirmDialog(null,"bạn có chắc chắn muốn thoát chương trình hay không","thông báo ",2)==0)
            this.dispose();
        
        
    }//GEN-LAST:event_btExitNXBActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddNXB;
    private javax.swing.JButton btEditNXB;
    private javax.swing.JButton btExitNXB;
    private javax.swing.JButton btnhap1;
    private javax.swing.JButton btxoanxb;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbnxb;
    private javax.swing.JTable tableNXB;
    private javax.swing.JTextField txtSearchNXB;
    private javax.swing.JTextField txtTenNXB;
    private javax.swing.JTextField txtdiachi;
    private javax.swing.JTextField txtmanxb;
    private javax.swing.JTextField txtphone;
    // End of variables declaration//GEN-END:variables
}
