/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Process.Them;
import static Process.Them.truyvanxau;
import static java.nio.file.Files.size;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author nguyenthienbao
 */
public class ThemSach extends javax.swing.JInternalFrame {

    /**
     * Creates new form ThemSach
     */
    public ThemSach() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bon_Them = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txt_MaNgonNgu = new javax.swing.JTextField();
        txt_MaTacGia = new javax.swing.JTextField();
        txt_MaNXB = new javax.swing.JTextField();
        txt_MaLinhVuc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_TenSach = new javax.swing.JTextField();
        txt_MaTuaSach = new javax.swing.JTextField();
        txt_SoTrang = new javax.swing.JTextField();
        txt_GiaSach = new javax.swing.JTextField();
        txt_SoLuong = new javax.swing.JTextField();
        radio = new javax.swing.JRadioButton();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÊM SÁCH");

        bon_Them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/button_ok.png"))); // NOI18N
        bon_Them.setText("Thêm");
        bon_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bon_ThemActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/button_cancel.png"))); // NOI18N
        jButton2.setText("Hủy");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/shutdown.png"))); // NOI18N
        jButton3.setText("Thoát");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin"));

        txt_MaTacGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MaTacGiaActionPerformed(evt);
            }
        });

        txt_MaNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MaNXBActionPerformed(evt);
            }
        });

        txt_MaLinhVuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MaLinhVucActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Mã Ngôn Ngữ:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Mã Tác Giả:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Mã NXB:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Mã Lĩnh Vực:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Tên Sách:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Mã Tựa Sách:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Giá Sách:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Số Trang:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Số Lượng:");

        txt_TenSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TenSachActionPerformed(evt);
            }
        });

        txt_MaTuaSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MaTuaSachActionPerformed(evt);
            }
        });

        radio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radio.setText("Cho Mượn");
        radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10))
                .addGap(91, 91, 91)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_TenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_MaTuaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_GiaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txt_SoTrang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_SoLuong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(101, 101, 101)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_MaNgonNgu, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_MaTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_MaNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_MaLinhVuc, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radio))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_TenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(txt_MaNgonNgu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_MaTuaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_MaTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_GiaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(txt_MaNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_SoTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(txt_MaLinhVuc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(radio))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(47, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bon_Them)
                        .addGap(88, 88, 88)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(jButton3)
                        .addGap(407, 407, 407))))
            .addGroup(layout.createSequentialGroup()
                .addGap(446, 446, 446)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bon_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_MaTuaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MaTuaSachActionPerformed
        // TODO add your handling code here:
        new ThemSach();
        this.dispose();
    }//GEN-LAST:event_txt_MaTuaSachActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txt_MaNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MaNXBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MaNXBActionPerformed

    private void txt_MaLinhVucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MaLinhVucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MaLinhVucActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        check = false;
        txt_GiaSach.setText("");
        txt_MaLinhVuc.setText("");
        txt_MaTuaSach.setText("");
        txt_MaNgonNgu.setText("");
        txt_MaNXB.setText("");
        txt_SoTrang.setText("");
        txt_MaTacGia.setText("");
        txt_TenSach.setText("");
        radio.setSelected(false);
        txt_SoLuong.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_TenSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TenSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TenSachActionPerformed

    private void txt_MaTacGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MaTacGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MaTacGiaActionPerformed

    private void bon_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bon_ThemActionPerformed
        // TODO add your handling code here:
        if (check == true){
            return;
        }
        check = true;
        int a = 0;
        String matuasach = txt_MaTuaSach.getText();
        Vector<String> vt; 
        String tensach = txt_TenSach.getText();
        String muon = muon();
        String giasach = txt_GiaSach.getText();
        String sotrang = txt_SoTrang.getText();
        String mangonngu = txt_MaNgonNgu.getText();
        String matacgia = txt_MaTacGia.getText();
        String maNXB = txt_MaNXB.getText();
        
        String malinhvuc = txt_MaLinhVuc.getText();
        
        if (tensach.equals("")==true){
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập tên sách");
            check = false;
            return;
        }
        if (giasach.equals(null)){
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập giá sách");
            check = false;
            return;
        }else {
            try{
                a = Integer.parseInt(giasach);
            }catch(NumberFormatException e1){
                JOptionPane.showMessageDialog(null, "Giá sách bị sai. Xin vui lòng nhập lại");
                check = false;
                return;
            }
            
        }
        
        if(sotrang.equals("")){
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập số trang của sách");
            check = false;
            return;
        }else{
            try{
                a = Integer.parseInt(sotrang);
            }catch(NumberFormatException e2){
                JOptionPane.showMessageDialog(null, "Số trang bị sai. Xin vui lòng nhập lại");
                check = false;
                return;
            }
        }
        vt = Them.truyvan("select distinct MaNgonNgu from tuasach where MaNgonNgu is not null");
        if (mangonngu.length() != 5){
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập mã ngôn ngữ hoặc nhập sai mã ngôn ngữ. Xin vui lòng kiểm tra lại");
            check = false;
            return;
        }else if (check(mangonngu,vt) == false){
            JOptionPane.showMessageDialog(null, "Mã ngôn ngữ hiện không có trong CSDL. XIn vui lòng kiểm tra lại hoặc thêm mã ngôn ngữ vào dữ liệu");
            check = false;
            return;
        }
        
        vt = Them.truyvan("select distinct MaTG from tuasach where MaTG is not null");
        if (matacgia.length() != 5){
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập mã tác giả hoặc nhập sai mã tác giả. Xin vui lòng kiểm tra lại");
            check = false;
            return;
        }else if (check(matacgia,vt) == false){
            JOptionPane.showMessageDialog(null, "Mã tacgia hiện không có trong CSDL. XIn vui lòng kiểm tra lại hoặc thêm mã tác giả vào dữ liệu");
            check = false;
            return;
        }
        
        vt = Them.truyvan("select distinct MaNXB from tuasach where MaNXB is not null");
        if (maNXB.length() != 6){
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập mã nhà xuất bản hoặc nhập sai mã nhaf xuất bản. Xin vui lòng kiểm tra lại");
            check = false;
            return;
        }else if (check(maNXB,vt) == false){
            JOptionPane.showMessageDialog(null, "Mã nhà xuất bản hiện không có trong CSDL. Xin vui lòng kiểm tra lại hoặc thêm mã nha xuất bản vào dữ liệu");
            check = false;
            return;
        }
        
        vt = Them.truyvan("select distinct maLV from tuasach where maLV is not null");
        if (malinhvuc.length() != 5){
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập mã lĩnh vực hoặc nhập sai mã linhx vực. Xin vui lòng kiểm tra lại");
            check = false;
            return;
        }else if (check(malinhvuc,vt) == false){
            JOptionPane.showMessageDialog(null, "Mã linh vực hiện không có trong CSDL. XIn vui lòng kiểm tra lại hoặc thêm mã lĩnh vực vào dữ liệu");
            check = false;
            return;
        }
        
        
        vt = Them.truyvan("select MaTuaSach from tuasach where tuasach.matuasach is not null");
        if (matuasach.length() != 2){
            JOptionPane.showMessageDialog(null, "Mã tựa sách đã sai");
            check = false;
            return;
        }else if (check(matuasach,vt) == false){
            Them.themSach("INSERT INTO tuasach (`MaTuaSach`, `TenSach`, `ChoMuon`, `GiaSach`, `SoTrang`, "
                    + "`MaNgonNgu`, `MaTG`, `MaNXB`, `MaLV`) VALUES ('"+matuasach+"', '"+tensach+"', "+muon()+", '"+giasach+"', '"+sotrang+"', '"+mangonngu+"', '"+matacgia+"', '"+maNXB+"', '"+malinhvuc+"')");
            
        }else {
            String str = truyvanxau("select tensach from tuasach where matuasach = '"+txt_MaTuaSach.getText()+"'");
            if (txt_TenSach.getText().equals(str)){
                JOptionPane.showMessageDialog(null, "Tên sách bị sai");
                return;
            }
        }
        
        int number = Integer.parseInt(txt_SoLuong.getText());
        int value = 0;
        for (int i = 0 ; i < number ; i++){
            vt = Them.truyvan("select masach from sach order by masach asc");
            value = laymasach(vt);
            Them.themSach("insert into sach values ('"+value+"','"+matuasach+"')");
        }
        JOptionPane.showMessageDialog(null, "Bạn đã thêm sách thành công");
        txt_TenSach.setText("");
        txt_MaTuaSach.setText("");
        txt_GiaSach.setText("");
        txt_SoTrang.setText("");
        txt_SoLuong.setText("");
        txt_MaNgonNgu.setText("");
        txt_MaTacGia.setText("");
        txt_MaNXB.setText("");
        txt_MaLinhVuc.setText("");
        
    }//GEN-LAST:event_bon_ThemActionPerformed

    private void radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioActionPerformed

    public boolean check(String str, Vector<String> vt){
        int size = vt.size();
        for (int i = 0; i < size; i++){
            if (vt.get(i).equals(str) == true){
                return true;
            }
        }
        return false;
    }
    
    public int number(String str){
        if (str.equals("")){
            return 0;
        }
        return Integer.parseInt(str);
    }
    
    public String muon(){
        if (radio.isSelected() == true){
            return "1";
        }
        return "0";
    }
    
    public int laymasach(Vector<String> vt){
        int size = vt.size();
        int tg = 1;
        for (int i = 0; i < size; i++){
            
            if (tg == Integer.parseInt(vt.get(i))){
                tg ++;
            }else {
                break;
            }
            
        }
        return tg;
    }

    private boolean check = false;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bon_Them;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton radio;
    private javax.swing.JTextField txt_GiaSach;
    private javax.swing.JTextField txt_MaLinhVuc;
    private javax.swing.JTextField txt_MaNXB;
    private javax.swing.JTextField txt_MaNgonNgu;
    private javax.swing.JTextField txt_MaTacGia;
    private javax.swing.JTextField txt_MaTuaSach;
    private javax.swing.JTextField txt_SoLuong;
    private javax.swing.JTextField txt_SoTrang;
    private javax.swing.JTextField txt_TenSach;
    // End of variables declaration//GEN-END:variables
}
